import { asyncHandler } from '../utils/asyncHandler.js';
import { AppError } from '../utils/errors.js';
import { collectionRefs } from '../services/firestore.js';
import { milkEntrySchema, milkPaymentSchema, milkSupplierSchema } from '../utils/validators.js';

const toDoc = doc => ({ id: doc.id, ...doc.data() });
const num = value => Number(value) || 0;
const dateKey = value => String(value || '').slice(0, 10);
const monthBounds = month => { const [year, monthIndex] = month.split('-').map(Number); return { start: `${month}-01`, end: new Date(year, monthIndex, 0).toISOString().slice(0, 10) }; };
const days = (start, end) => { const result = []; const current = new Date(`${start}T00:00:00`); const last = new Date(`${end}T00:00:00`); while (current <= last) { result.push(current.toISOString().slice(0, 10)); current.setDate(current.getDate() + 1); } return result; };
const ensure = async (id, uid) => { const doc = await collectionRefs.milkSuppliers().doc(id).get(); if (!doc.exists || doc.data().userId !== uid) throw new AppError('Supplier not found', 404); return toDoc(doc); };
const entriesFor = async (supplierId, uid) => (await collectionRefs.milkEntries().where('supplierId', '==', supplierId).get()).docs.map(toDoc).filter(item => item.userId === uid);
const summary = (supplier, entries, month, payments = []) => { const { start, end } = monthBounds(month); const today = new Date().toISOString().slice(0, 10); const configuredStart = supplier.startDate && supplier.startDate > start ? supplier.startDate : start; const list = entries.filter(item => item.date >= start && item.date <= end).sort((a, b) => a.date.localeCompare(b.date)); const firstSavedDate = list.length ? list[0].date : ''; const rangeStart = [configuredStart, firstSavedDate].filter(Boolean).sort()[0] || start; const latestSavedDate = list.length ? list[list.length - 1].date : ''; const currentEnd = [end < today ? end : today, latestSavedDate].filter(Boolean).sort().pop(); const totalMilk = list.reduce((sum, item) => sum + num(item.quantityKg), 0); const totalAmount = list.reduce((sum, item) => sum + num(item.amount), 0); const receivedDays = list.length; const entriesByDate = new Map(); list.forEach(item => entriesByDate.set(item.date, [...(entriesByDate.get(item.date) || []), item])); const generatedCalendar = rangeStart <= currentEnd ? days(rangeStart, currentEnd).flatMap(date => (entriesByDate.get(date) || []).length ? entriesByDate.get(date).map(item => ({ date, status: 'Received', ...item })) : date < today ? [{ date, status: 'Naga' }] : date === today ? [{ date, status: 'Pending' }] : []) : []; const calendar = generatedCalendar.length ? generatedCalendar : list.map(item => ({ ...item, status: 'Received' }));
  const nagaDays = calendar.filter(item => item.status === 'Naga').length; const paid = payments.filter(item => item.month === month).reduce((sum, item) => sum + num(item.amountPaid), 0);
  return { month, startDate: rangeStart, endDate: end, totalMilk, totalAmount, receivedDays, nagaDays, averageMilk: receivedDays ? totalMilk / receivedDays : 0, calendar, payment: { totalPayable: totalAmount, amountPaid: paid, balance: totalAmount - paid, status: paid >= totalAmount && totalAmount ? 'Paid' : paid ? 'Partial' : 'Unpaid' } };
};

export const listSuppliers = asyncHandler(async (req, res) => { const suppliers = (await collectionRefs.milkSuppliers().where('userId', '==', req.user.uid).get()).docs.map(toDoc); const month = req.query.month || new Date().toISOString().slice(0, 7); const result = await Promise.all(suppliers.map(async supplier => { const entries = await entriesFor(supplier.id, req.user.uid); const payments = (await collectionRefs.milkPayments().where('supplierId', '==', supplier.id).get()).docs.map(toDoc).filter(item => item.userId === req.user.uid); const totalRemaining = entries.reduce((sum, item) => sum + num(item.amount), 0) - payments.reduce((sum, item) => sum + num(item.amountPaid), 0); const monthly = summary(supplier, entries, month, payments); return { ...supplier, monthly: { ...monthly, payment: { ...monthly.payment, balance: totalRemaining } }, totalRemaining }; })); res.json({ suppliers: result }); });
export const createSupplier = asyncHandler(async (req, res) => { const payload = milkSupplierSchema.parse(req.body); const doc = { ...payload, ratePerKg: num(payload.ratePerKg), userId: req.user.uid, createdAt: new Date().toISOString(), rateHistory: payload.ratePerKg ? [{ rate: num(payload.ratePerKg), effectiveDate: payload.startDate || new Date().toISOString().slice(0, 10) }] : [] }; const ref = collectionRefs.milkSuppliers().doc(); await ref.set(doc); res.status(201).json({ supplier: { id: ref.id, ...doc } }); });
export const getSupplier = asyncHandler(async (req, res) => { const supplier = await ensure(req.params.supplierId, req.user.uid); const month = req.query.month || new Date().toISOString().slice(0, 7); const entries = await entriesFor(supplier.id, req.user.uid); const payments = (await collectionRefs.milkPayments().where('supplierId', '==', supplier.id).get()).docs.map(toDoc).filter(item => item.userId === req.user.uid); res.json({ supplier, entries, monthly: summary(supplier, entries, month, payments) }); });
export const updateSupplier = asyncHandler(async (req, res) => { const current = await ensure(req.params.supplierId, req.user.uid); const payload = milkSupplierSchema.partial().parse(req.body); const update = { ...payload }; if (payload.ratePerKg !== undefined && num(payload.ratePerKg) !== num(current.ratePerKg)) update.rateHistory = [...(current.rateHistory || []), { rate: num(payload.ratePerKg), effectiveDate: new Date().toISOString().slice(0, 10) }]; await collectionRefs.milkSuppliers().doc(current.id).set(update, { merge: true }); res.json({ supplier: await ensure(current.id, req.user.uid) }); });
export const saveEntry = asyncHandler(async (req, res) => { const supplier = await ensure(req.params.supplierId, req.user.uid); const payload = milkEntrySchema.parse(req.body); const found = (await entriesFor(supplier.id, req.user.uid)).find(item => item.date === payload.date); const ratePerKg = payload.ratePerKg === undefined ? num(supplier.ratePerKg) : num(payload.ratePerKg); const doc = { supplierId: supplier.id, date: payload.date, quantityKg: num(payload.quantityKg), ratePerKg, amount: num(payload.quantityKg) * ratePerKg, notes: payload.notes || '', userId: req.user.uid, updatedAt: new Date().toISOString() }; if (found) { await collectionRefs.milkEntries().doc(found.id).set(doc, { merge: true }); return res.json({ entry: { id: found.id, ...doc } }); } const ref = collectionRefs.milkEntries().doc(); await ref.set({ ...doc, createdAt: doc.updatedAt }); res.status(201).json({ entry: { id: ref.id, ...doc } }); });
export const deleteEntry = asyncHandler(async (req, res) => { const doc = await collectionRefs.milkEntries().doc(req.params.entryId).get(); if (!doc.exists || doc.data().userId !== req.user.uid || doc.data().supplierId !== req.params.supplierId) throw new AppError('Milk entry not found', 404); await doc.ref.delete(); res.json({ message: 'Milk entry deleted' }); });
export const savePayment = asyncHandler(async (req, res) => { await ensure(req.params.supplierId, req.user.uid); const payload = milkPaymentSchema.parse(req.body); const doc = { ...payload, amountPaid: num(payload.amountPaid), supplierId: req.params.supplierId, userId: req.user.uid, createdAt: new Date().toISOString() }; const ref = collectionRefs.milkPayments().doc(); await ref.set(doc); res.status(201).json({ payment: { id: ref.id, ...doc } }); });
