import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../lib/api';
import { Button, Card, Input, LoadingState, SectionHeader, Select, StatCard, Table, Textarea } from '../components/ui';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';

const activityTypes = ['Land Preparation', 'Seed / Sowing', 'Fertilizer', 'Spray / Pesticide', 'Irrigation', 'Labour', 'Machinery', 'Other Expense', 'Harvesting'];
const emptyActivity = { type: 'Land Preparation', date: '', title: '', quantity: '', unit: '', totalCost: '', detailLabel: '', detailValue: '', notes: '' };
const emptyYield = { date: '', harvestNumber: '1st Harvest', totalProduction: '', unit: 'Maund', bags: '0', weightPerBag: '0', quality: '', moisture: '', storedQuantity: '0', soldQuantity: '0', notes: '' };
const emptySale = { saleDate: '', buyerName: '', quantitySold: '', unit: 'Maund', ratePerUnit: '', transportCost: '0', marketCharges: '0', commission: '0', otherDeduction: '0', paymentStatus: 'Pending', amountReceived: '0', notes: '' };
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;
const steps = crop => crop === 'Rice' ? ['Nursery', 'Land Preparation', 'Transplanting', 'Fertilizer', 'Irrigation', 'Spray', 'Harvest', 'Sale'] : crop === 'Cotton' ? ['Land Preparation', 'Sowing', 'Fertilizer', 'Irrigation', 'Spray', 'Pickings', 'Sale'] : ['Land Preparation', 'Sowing', 'Fertilizer', 'Irrigation', 'Spray', 'Harvest', 'Sale'];

export default function CropDashboard() {
  const { seasonId } = useParams(); const navigate = useNavigate(); const [data, setData] = useState(null); const [tab, setTab] = useState('Overview'); const [activity, setActivity] = useState(emptyActivity); const [yieldForm, setYieldForm] = useState(emptyYield); const [saleForm, setSaleForm] = useState(emptySale); const [saving, setSaving] = useState(false);
  const load = async () => { try { setData((await api.get(`/crops/${seasonId}/dashboard`)).data); } catch (err) { toast.error(err.response?.data?.message || err.message); } };
  useEffect(() => { load(); }, [seasonId]);
  const change = set => key => e => set(old => ({ ...old, [key]: e.target.value }));
  const save = async (event, endpoint, payload, reset) => { event.preventDefault(); setSaving(true); try { await api.post(`/crops/${seasonId}/${endpoint}`, payload); toast.success('Record saved'); reset(); await load(); } catch (err) { Swal.fire({ icon: 'error', title: 'Could not save record', text: err.response?.data?.message || err.message, confirmButtonColor: '#001e00' }); } finally { setSaving(false); } };
  const remove = async (type, id) => { const answer = await Swal.fire({ title: 'Delete this record?', text: 'This cannot be undone.', icon: 'warning', showCancelButton: true, confirmButtonColor: '#b91c1c', cancelButtonColor: '#001e00' }); if (!answer.isConfirmed) return; try { await api.delete(`/crops/${seasonId}/${type}/${id}`); toast.success('Record deleted'); load(); } catch (err) { toast.error(err.response?.data?.message || err.message); } };
  if (!data) return <div className="min-h-screen bg-[#f4f7f4] p-5"><div className="mx-auto max-w-6xl"><LoadingState label="Loading crop dashboard..." /></div></div>;
  const { season, summary, activities, yields, sales, timeline } = data;
  const tabs = ['Overview', 'Activities', 'Yield', 'Sales', 'Timeline'];
  return <div className="min-h-screen bg-[#f4f7f4] p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><SectionHeader title={`${season.cropName} · ${season.season}`} subtitle={`${season.fieldName ? `${season.fieldName} · ` : ''}${season.totalArea} ${season.areaUnit} · ${season.status}`} action={<Button variant="secondary" onClick={() => navigate('/crops')}>Back to crops</Button>} /><Card><div className="flex flex-wrap items-center gap-2">{steps(season.cropName).map((step, i) => <div key={step} className="flex items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${i < 2 || activities.some(a => a.type.includes(step) || a.title.toLowerCase().includes(step.toLowerCase())) ? 'bg-[#d6f0d6]' : 'bg-[#f0faf0] text-[#3a8a3a]'}`}>{step}</span>{i < steps(season.cropName).length - 1 ? <span className="text-[#6ab86a]">→</span> : null}</div>)}</div></Card><div className="flex flex-wrap gap-2 border-b border-[#a8d8a8] pb-3">{tabs.map(item => <Button key={item} variant={tab === item ? 'primary' : 'secondary'} onClick={() => setTab(item)}>{item}</Button>)}</div>
    {tab === 'Overview' ? <><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5"><StatCard title="Total area" value={`${season.totalArea} ${season.areaUnit}`} /><StatCard title="Investment" value={money(summary.totalInvestment)} /><StatCard title="Cost / acre" value={money(summary.costPerAcre)} /><StatCard title="Total yield" value={summary.totalProduction.toLocaleString()} /><StatCard title="Yield / acre" value={summary.yieldPerAcre.toFixed(2)} /><StatCard title="Revenue" value={money(summary.totalRevenue)} /><StatCard title="Net profit / loss" value={money(summary.netProfit)} /><StatCard title="Profit / acre" value={money(summary.profitPerAcre)} /><StatCard title="ROI" value={`${summary.roi.toFixed(1)}%`} /><StatCard title="Irrigations" value={summary.irrigationCount} /></div><Card><div className="mb-4 text-lg font-bold text-[#001e00]">Investment by activity</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(summary.costsByType).map(([type, cost]) => <div key={type} className="rounded-xl bg-[#f0faf0] p-4"><div className="text-sm text-[#3a8a3a]">{type}</div><div className="mt-1 text-lg font-bold">{money(cost)}</div></div>)}</div></Card></> : null}
    {tab === 'Activities' ? <div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><Card><form className="grid gap-4" onSubmit={e => save(e, 'activities', { ...activity, details: { [activity.detailLabel || 'Detail']: activity.detailValue } }, () => setActivity(emptyActivity))}><div className="text-lg font-bold">Add activity / expense</div><Select label="Section" value={activity.type} onChange={change(setActivity)('type')}>{activityTypes.map(type => <option key={type}>{type}</option>)}</Select><Input label="Date" type="date" value={activity.date} onChange={change(setActivity)('date')} required /><Input label="Activity / product" value={activity.title} onChange={change(setActivity)('title')} placeholder="e.g. 1st DAP application" required /><div className="grid grid-cols-2 gap-3"><Input label="Quantity" type="number" min="0" value={activity.quantity} onChange={change(setActivity)('quantity')} /><Input label="Unit" value={activity.unit} onChange={change(setActivity)('unit')} placeholder="Bags, hours, acres" /></div><Input label="Total cost" type="number" min="0" value={activity.totalCost} onChange={change(setActivity)('totalCost')} required /><div className="grid grid-cols-2 gap-3"><Input label="Detail label" value={activity.detailLabel} onChange={change(setActivity)('detailLabel')} placeholder="e.g. Fertilizer type" /><Input label="Detail value" value={activity.detailValue} onChange={change(setActivity)('detailValue')} placeholder="e.g. DAP" /></div><Textarea label="Notes" rows="2" value={activity.notes} onChange={change(setActivity)('notes')} /><Button type="submit" disabled={saving}>Save activity</Button></form></Card><Table rows={activities} columns={[{ key: 'date', label: 'Date' }, { key: 'type', label: 'Section' }, { key: 'title', label: 'Activity' }, { key: 'quantity', label: 'Quantity', render: row => `${row.quantity || '-'} ${row.unit || ''}` }, { key: 'totalCost', label: 'Cost', render: row => money(row.totalCost) }, { key: 'actions', label: '', render: row => <Button variant="danger" onClick={() => remove('activities', row.id)}>Delete</Button> }]} emptyMessage="No activity records yet." /></div> : null}
    {tab === 'Yield' ? <div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><Card><form className="grid gap-4" onSubmit={e => save(e, 'yields', yieldForm, () => setYieldForm(emptyYield))}><div className="text-lg font-bold">Add yield / production</div><Input label="Harvest / picking number" value={yieldForm.harvestNumber} onChange={change(setYieldForm)('harvestNumber')} required /><Input label="Date" type="date" value={yieldForm.date} onChange={change(setYieldForm)('date')} required /><div className="grid grid-cols-2 gap-3"><Input label="Total production" type="number" min="0" value={yieldForm.totalProduction} onChange={change(setYieldForm)('totalProduction')} required /><Select label="Unit" value={yieldForm.unit} onChange={change(setYieldForm)('unit')}><option>Kg</option><option>Maund</option><option>Ton</option><option>Bags</option></Select></div><div className="grid grid-cols-2 gap-3"><Input label="Number of bags" type="number" min="0" value={yieldForm.bags} onChange={change(setYieldForm)('bags')} /><Input label="Weight per bag" type="number" min="0" value={yieldForm.weightPerBag} onChange={change(setYieldForm)('weightPerBag')} /></div><Input label="Quality / grade" value={yieldForm.quality} onChange={change(setYieldForm)('quality')} /><Textarea label="Notes" rows="2" value={yieldForm.notes} onChange={change(setYieldForm)('notes')} /><Button type="submit" disabled={saving}>Save yield</Button></form></Card><Table rows={yields} columns={[{ key: 'date', label: 'Date' }, { key: 'harvestNumber', label: 'Harvest' }, { key: 'totalProduction', label: 'Production', render: row => `${row.totalProduction} ${row.unit}` }, { key: 'quality', label: 'Quality' }, { key: 'actions', label: '', render: row => <Button variant="danger" onClick={() => remove('yields', row.id)}>Delete</Button> }]} emptyMessage="No yield records yet." /></div> : null}
    {tab === 'Sales' ? <div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><Card><form className="grid gap-4" onSubmit={e => save(e, 'sales', saleForm, () => setSaleForm(emptySale))}><div className="text-lg font-bold">Add crop sale</div><Input label="Sale date" type="date" value={saleForm.saleDate} onChange={change(setSaleForm)('saleDate')} required /><Input label="Buyer / dealer name" value={saleForm.buyerName} onChange={change(setSaleForm)('buyerName')} required /><div className="grid grid-cols-2 gap-3"><Input label="Quantity sold" type="number" min="0" value={saleForm.quantitySold} onChange={change(setSaleForm)('quantitySold')} required /><Select label="Unit" value={saleForm.unit} onChange={change(setSaleForm)('unit')}><option>Kg</option><option>Maund</option><option>Ton</option><option>Bags</option></Select></div><Input label="Rate per unit" type="number" min="0" value={saleForm.ratePerUnit} onChange={change(setSaleForm)('ratePerUnit')} required /><div className="grid grid-cols-2 gap-3"><Input label="Transport cost" type="number" min="0" value={saleForm.transportCost} onChange={change(setSaleForm)('transportCost')} /><Input label="Mandi charges" type="number" min="0" value={saleForm.marketCharges} onChange={change(setSaleForm)('marketCharges')} /><Input label="Commission" type="number" min="0" value={saleForm.commission} onChange={change(setSaleForm)('commission')} /><Input label="Other deductions" type="number" min="0" value={saleForm.otherDeduction} onChange={change(setSaleForm)('otherDeduction')} /></div><Select label="Payment status" value={saleForm.paymentStatus} onChange={change(setSaleForm)('paymentStatus')}><option>Paid</option><option>Partial</option><option>Pending</option></Select><Input label="Amount received" type="number" min="0" value={saleForm.amountReceived} onChange={change(setSaleForm)('amountReceived')} /><Textarea label="Notes" rows="2" value={saleForm.notes} onChange={change(setSaleForm)('notes')} /><Button type="submit" disabled={saving}>Save sale</Button></form></Card><Table rows={sales} columns={[{ key: 'saleDate', label: 'Date' }, { key: 'buyerName', label: 'Buyer' }, { key: 'quantitySold', label: 'Quantity', render: row => `${row.quantitySold} ${row.unit}` }, { key: 'netSaleAmount', label: 'Net sale', render: row => money(row.netSaleAmount) }, { key: 'paymentStatus', label: 'Payment' }, { key: 'actions', label: '', render: row => <Button variant="danger" onClick={() => remove('sales', row.id)}>Delete</Button> }]} emptyMessage="No crop sales yet." /></div> : null}
    {tab === 'Timeline' ? <Card><div className="space-y-4">{timeline.length ? timeline.map(item => <div key={`${item.type}-${item.id}`} className="border-l-2 border-[#a8d8a8] pl-4"><div className="text-xs font-semibold text-[#d2b45a]">{item.date}</div><div className="font-semibold text-[#001e00]">{item.title}</div><div className="text-sm text-[#3a8a3a]">{item.type}{item.detail ? ` · ${item.detail}` : ''}</div></div>) : <div className="py-8 text-center text-[#3a8a3a]">Your crop history will appear here as you add records.</div>}</div></Card> : null}
  </div></div>;
}
