import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../lib/api';
import { Button, Card, EmptyState, Input, LoadingState, SectionHeader, Select, Textarea } from '../components/ui';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';

const crops = [['Rice', 'Chawal'], ['Wheat', 'Gandum'], ['Cotton', 'Kapas'], ['Sugarcane', 'Ganna'], ['Maize', 'Makai'], ['Other Crop', 'Custom crop']];
const blank = name => ({ cropName: name === 'Other Crop' ? '' : name, variety: '', season: String(new Date().getFullYear()), fieldName: '', totalArea: '', areaUnit: 'Acre', sowingDate: '', expectedHarvestDate: '', landOwnership: 'Own', rentCost: '0', notes: '', status: 'Planned' });

export default function Crops() {
  const navigate = useNavigate();
  const [seasons, setSeasons] = useState([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(''); const [form, setForm] = useState(blank('')); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { setSeasons((await api.get('/crops')).data.seasons); } catch (err) { toast.error(err.response?.data?.message || err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const counts = useMemo(() => seasons.reduce((map, item) => ({ ...map, [item.cropName]: (map[item.cropName] || 0) + 1 }), {}), [seasons]);
  const field = key => event => setForm(value => ({ ...value, [key]: event.target.value }));
  const openSetup = name => { setSelected(name); setForm(blank(name)); };
  const submit = async event => { event.preventDefault(); setSaving(true); try { const response = await api.post('/crops', form); toast.success('Crop season created'); navigate(`/crops/${response.data.season.id}`); } catch (err) { Swal.fire({ icon: 'error', title: 'Could not save crop season', text: err.response?.data?.message || err.message, confirmButtonColor: '#001e00' }); } finally { setSaving(false); } };
  if (selected) return <div className="min-h-screen bg-[#f4f7f4] p-5 md:p-8"><div className="mx-auto max-w-5xl"><SectionHeader title={`New ${selected} season`} subtitle="Keep each crop, field, and season as a separate record." action={<Button variant="secondary" onClick={() => setSelected('')}>Back</Button>} /><Card><form className="grid gap-4 md:grid-cols-3" onSubmit={submit}>
    {selected === 'Other Crop' ? <Input label="Crop name" value={form.cropName} onChange={field('cropName')} required /> : <Input label="Crop name" value={form.cropName} readOnly />}
    <Input label="Variety / seed type" value={form.variety} onChange={field('variety')} /><Input label="Season / year" value={form.season} onChange={field('season')} placeholder="Rabi 2026" required /><Input label="Field / land name (optional)" value={form.fieldName} onChange={field('fieldName')} />
    <Input label="Total area" type="number" min="0.01" step="0.01" value={form.totalArea} onChange={field('totalArea')} required /><Select label="Area unit" value={form.areaUnit} onChange={field('areaUnit')}><option>Acre</option><option>Kanal</option><option>Marla</option></Select><Input label="Sowing date" type="date" value={form.sowingDate} onChange={field('sowingDate')} /><Input label="Expected harvest date" type="date" value={form.expectedHarvestDate} onChange={field('expectedHarvestDate')} />
    <Select label="Land ownership" value={form.landOwnership} onChange={field('landOwnership')}><option>Own</option><option>Rented / Theka</option></Select>{form.landOwnership === 'Rented / Theka' ? <Input label="Rent / theka cost" type="number" min="0" value={form.rentCost} onChange={field('rentCost')} /> : null}<Select label="Status" value={form.status} onChange={field('status')}><option>Planned</option><option>Active</option><option>Harvested</option><option>Sold</option><option>Closed</option></Select>
    <div className="md:col-span-3"><Textarea label="Notes" rows="3" value={form.notes} onChange={field('notes')} /></div><div className="md:col-span-3"><Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Create crop season'}</Button></div>
  </form></Card></div></div>;
  return <div className="min-h-screen bg-[#f4f7f4] p-5 md:p-8"><div className="mx-auto max-w-6xl space-y-8"><SectionHeader title="Crop Management" subtitle="Manage crops from land preparation through harvest and final sale." action={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => navigate('/')}>All modules</Button><Button variant="secondary" onClick={() => navigate('/crops/reports')}>Reports</Button><Button onClick={() => openSetup('Other Crop')}>Add custom crop</Button></div>} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{crops.map(([name, local]) => <button key={name} type="button" onClick={() => openSetup(name)} className="rounded-2xl border border-[#a8d8a8] bg-white p-5 text-left shadow-card transition hover:-translate-y-0.5 hover:border-[#3a8a3a]"><div className="text-xs font-bold uppercase tracking-[0.16em] text-[#d2b45a]">{local}</div><div className="mt-2 text-xl font-bold text-[#001e00]">{name}</div><div className="mt-4 text-sm text-[#3a8a3a]">{counts[name] || 0} saved seasons · Add or open</div></button>)}</div><section><SectionHeader title="Saved crop seasons" subtitle="Open a season to view its costs, operations, yield, sales, and profit." />{loading ? <LoadingState label="Loading crop seasons..." /> : !seasons.length ? <EmptyState title="No crop seasons yet" description="Select one of the crop cards above to start your first record." /> : <div className="grid gap-4 md:grid-cols-2">{seasons.map(item => <Card key={item.id} className="flex flex-col justify-between gap-4"><div><div className="flex justify-between gap-3"><div><div className="text-xl font-bold text-[#001e00]">{item.cropName}</div><div className="mt-1 text-sm text-[#3a8a3a]">{item.variety || 'No variety'} · {item.season}</div></div><span className="h-fit rounded-full bg-[#d6f0d6] px-3 py-1 text-xs font-semibold">{item.status}</span></div><div className="mt-4 text-sm text-[#3a8a3a]">{item.fieldName ? `${item.fieldName} · ` : ''}{item.totalArea} {item.areaUnit}</div></div><Button onClick={() => navigate(`/crops/${item.id}`)}>Open dashboard</Button></Card>)}</div>}</section></div></div>;
}
