import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../lib/api';
import { Button, Card, EmptyState, Input, LoadingState, SectionHeader, Select, Table, Textarea } from '../components/ui';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';

const blank = { name: '', phone: '', address: '', startDate: '', ratePerKg: '', status: 'Active', notes: '' };
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;
export default function Dairy() {
  const navigate = useNavigate(); const [suppliers, setSuppliers] = useState([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { setSuppliers((await api.get('/dairy/suppliers')).data.suppliers); } catch (err) { toast.error(err.response?.data?.message || err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); const change = key => event => setForm(current => ({ ...current, [key]: event.target.value }));
  const submit = async event => { event.preventDefault(); setSaving(true); try { const res = await api.post('/dairy/suppliers', form); toast.success('Supplier added'); navigate(`/dairy/${res.data.supplier.id}`); } catch (err) { Swal.fire({ icon: 'error', title: 'Could not add supplier', text: err.response?.data?.message || err.message, confirmButtonColor: '#001e00' }); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-[#f4f7f4] p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><SectionHeader title="Dairy / Milk Collection" subtitle="Manage milk suppliers, their daily collection, current rate, and monthly payments." action={<Button variant="secondary" onClick={() => navigate('/')}>All modules</Button>} /><div className="grid gap-6 xl:grid-cols-[380px_1fr]"><Card><form className="grid gap-4" onSubmit={submit}><div className="text-lg font-bold">Add milk supplier</div><Input label="Supplier name *" value={form.name} onChange={change('name')} required /><Input label="Phone number" value={form.phone} onChange={change('phone')} /><Input label="Address / village" value={form.address} onChange={change('address')} /><Input label="Start date" type="date" value={form.startDate} onChange={change('startDate')} /><Input label="Milk rate per Kg (Rs.)" type="number" min="0" value={form.ratePerKg} onChange={change('ratePerKg')} /><Select label="Status" value={form.status} onChange={change('status')}><option>Active</option><option>Inactive</option></Select><Textarea label="Notes" rows="2" value={form.notes} onChange={change('notes')} /><Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Add supplier'}</Button></form></Card><div>{loading ? <LoadingState label="Loading suppliers..." /> : !suppliers.length ? <EmptyState title="No milk suppliers yet" description="Add your first supplier from the form." /> : <Table rows={suppliers} columns={[{ key: 'name', label: 'Supplier' }, { key: 'rate', label: 'Rate / Kg', render: row => money(row.ratePerKg) }, { key: 'milk', label: 'This month milk', render: row => `${Number(row.monthly?.totalMilk || 0).toLocaleString()} Kg` }, { key: 'amount', label: 'Amount', render: row => money(row.monthly?.totalAmount) }, { key: 'naga', label: 'Naga', render: row => row.monthly?.nagaDays || 0 }, { key: 'status', label: 'Status' }, { key: 'actions', label: '', render: row => <Button onClick={() => navigate(`/dairy/${row.id}`)}>Open</Button> }]} />}</div></div></div></div>;
}
