import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../lib/api';
import { Button, Card, Input, LoadingState, SectionHeader, Select, Textarea } from '../components/ui';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';

const blank = { name: '', phone: '', address: '', startDate: '', ratePerKg: '', status: 'Active', notes: '' };
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;
const today = () => new Date().toISOString().slice(0, 10);

export default function Dairy() {
  const navigate = useNavigate();
  const [suppliers, setSuppliers] = useState([]); const [form, setForm] = useState(blank); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [entryDate, setEntryDate] = useState(today()); const [quantities, setQuantities] = useState({}); const [savingSupplier, setSavingSupplier] = useState('');
  const load = async () => { setLoading(true); try { setSuppliers((await api.get('/dairy/suppliers')).data.suppliers); } catch (err) { toast.error(err.response?.data?.message || err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = key => event => setForm(current => ({ ...current, [key]: event.target.value }));
  const submit = async event => { event.preventDefault(); setSaving(true); try { await api.post('/dairy/suppliers', form); toast.success('Supplier added'); setForm(blank); setShowForm(false); await load(); } catch (err) { Swal.fire({ icon: 'error', title: 'Could not add supplier', text: err.response?.data?.message || err.message, confirmButtonColor: '#001e00' }); } finally { setSaving(false); } };
  const saveMilk = async supplier => { const quantityKg = quantities[supplier.id]; if (quantityKg === '' || quantityKg === undefined) return toast.error('Enter milk quantity first.'); setSavingSupplier(supplier.id); try { await api.post(`/dairy/suppliers/${supplier.id}/entries`, { date: entryDate, quantityKg }); toast.success(`${supplier.name}'s milk saved`); setQuantities(current => ({ ...current, [supplier.id]: '' })); await load(); } catch (err) { toast.error(err.response?.data?.message || err.message); } finally { setSavingSupplier(''); } };
  const active = suppliers.filter(item => item.status === 'Active');
  const formCard = <Card><form className="grid gap-4" onSubmit={submit}><div className="flex items-center justify-between"><div className="text-lg font-bold">Add milk supplier</div>{suppliers.length ? <Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Close</Button> : null}</div><Input label="Supplier name *" value={form.name} onChange={change('name')} required /><Input label="Phone number" value={form.phone} onChange={change('phone')} /><Input label="Address / village" value={form.address} onChange={change('address')} /><Input label="Start date" type="date" value={form.startDate} onChange={change('startDate')} /><Input label="Milk rate per Kg (Rs.)" type="number" min="0" value={form.ratePerKg} onChange={change('ratePerKg')} /><Select label="Status" value={form.status} onChange={change('status')}><option>Active</option><option>Inactive</option></Select><Textarea label="Notes" rows="2" value={form.notes} onChange={change('notes')} /><Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Add supplier'}</Button></form></Card>;
  return <div className="min-h-screen bg-[#f4f7f4] p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><SectionHeader title="Dairy / Milk Collection" subtitle="Enter today's milk for every supplier directly from this page." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => navigate('/')}>All modules</Button>{suppliers.length && !showForm ? <Button onClick={() => setShowForm(true)}>+ Add supplier</Button> : null}</div>} />{loading ? <LoadingState label="Loading suppliers..." /> : <>{!suppliers.length || showForm ? <div className={suppliers.length ? 'max-w-md' : 'mx-auto max-w-md'}>{formCard}</div> : null}<Card><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-lg font-bold">Daily milk entry</div><div className="text-sm text-[#3a8a3a]">Any past date without an entry is counted as Naga.</div></div><Input label="Entry date" type="date" value={entryDate} onChange={event => setEntryDate(event.target.value)} className="sm:w-48" /></div>{active.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map(supplier => <div key={supplier.id} className="rounded-2xl border border-[#a8d8a8] bg-[#fafffa] p-4"><div className="flex items-start justify-between gap-3"><button type="button" onClick={() => navigate(`/dairy/${supplier.id}`)} className="text-left"><div className="text-lg font-bold text-[#001e00]">{supplier.name}</div><div className="text-sm text-[#3a8a3a]">Rate: {money(supplier.ratePerKg)} / Kg</div></button><span className="rounded-full bg-[#d6f0d6] px-2 py-1 text-xs font-semibold">Naga: {supplier.monthly?.nagaDays || 0}</span></div><div className="mt-4 flex gap-2"><input type="number" min="0" step="0.01" value={quantities[supplier.id] || ''} onChange={event => setQuantities(current => ({ ...current, [supplier.id]: event.target.value }))} placeholder="Today's milk (Kg)" className="min-w-0 flex-1 rounded-xl border border-[#a8d8a8] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#001e00]" /><Button onClick={() => saveMilk(supplier)} disabled={savingSupplier === supplier.id}>{savingSupplier === supplier.id ? 'Saving...' : 'Save'}</Button></div><div className="mt-3 text-xs text-[#3a8a3a]">This month: {Number(supplier.monthly?.totalMilk || 0).toLocaleString()} Kg · {money(supplier.monthly?.totalAmount)}</div></div>)}</div> : <div className="py-10 text-center text-[#3a8a3a]">No active suppliers. Add one using + Add supplier.</div>}</Card></>}</div></div>;
}
